openapi: 3.0.3
info:
  title: Movie App API
  version: 1.0.0
servers:
  - url: http://localhost:3000

paths:
  /auth/register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/AuthResponse' }
        '409':
          description: User already exists
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /auth/login:
    post:
      tags: [Auth]
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in
          content:
            application/json:
              schema: { $ref: '#/components/schemas/AuthResponse' }
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /movies/{id}:
    get:
      tags: [Movies]
      summary: Get a movie by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Movie retrieved
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Movie' }
        '400':
          description: Bad request
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
components:
  schemas:
    RegisterRequest:
      type: object
      required: [first_name, last_name, email, password]
      properties:
        first_name: 
         type: string 
         example: Jay 
        last_name:   
          type: string 
          example: V 
        email:      
          type: string
          format: email 
        password:   
          type: string
          format: password
          minLength: 8

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:      
          type: string
          format: email 
        password:   
          type: string
          format: password
          minLength: 8

    Movie:
    type: object
    properties:
      id:
        type: integer
        example: 1

      title:
        type: string
        example: "Inception"

      overview:
        type: string
        nullable: true
        example: "A thief who steals corporate secrets through dream-sharing technology."

      releaseYear:
        type: string
        example: "2010"

      genres:
        type: array
        items:
          type: string
        example:
          - "Sci-Fi"
          - "Thriller"

      runtime:
        type: integer
        nullable: true
        example: 148

      posterUrl:
        type: string
        format: uri
        nullable: true
        example: "https://example.com/posters/inception.jpg"

      createdBy:
        type: integer
        example: 5
        



    AuthResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            name:   
              type: string 
            email:  
              type: string
              format: email 
        token: 
          type: string 
    Error:
      type: object
      properties:
        statusCode:
          type: integer
          example: 409
        message:
          type: string
          example: User Already Exist
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT